[package]
name = "godot-kotlin-jvm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.17.0"
gdnative = { path = "gdnative"}

[workspace]
members = [
    "gdnative"
]